### ISSUE TITLE
mlWatch fails when xqy or xslt is invalid

### ISSUE THREAD

**Issue by sastafford** [rjrudin/marklogic-java#46] opened 2015-01-26 19:58 UTC
When I have mlWatch on, it would be nice if it just logged out an invalid xqy or xslt file as opposed to just failing.  I have to restart everytime I save something that is invalid or not well formed.

**Comment by rjrudin** [comment] 2015-01-27 00:05
Dupe of #35

**Closed by rjrudin** 2015-01-27 00:05 UTC
Labels: enhancement
